type CartItem {
  uid:       ID!
  product:   Product!
  date:      String!
  time:      String!
  partySize: Int!
  price:     Float!
}

type Cart {
  items:      [CartItem!]!
  itemCount:  Int!
  totalPrice: Float!
}

input CartItemInput {
  tourId:    String
  cruiseId:  String
  date:      String!
  time:      String!
  partySize: Int!
  price:     Float!
}

extend type Query {
  cart(sessionId: String!): Cart!
}

type Mutation {
  addToCart(sessionId: String!, input: CartItemInput!): Cart!
  removeFromCart(sessionId: String!, uid: ID!):         Cart!
  clearCart(sessionId: String!):                        Cart!
}
