type TourCategory {
  id: ID!
  slug: String!
  label: String!
}

type Region {
  id: ID!
  key: String!
  label: String!
  image: String!
  cities: [City!]!
}

type City {
  id: ID!
  name: String!
  region: Region!
}

type Tour {
  id:           ID!
  title:        String!
  description:  String!
  itinerary:    String!
  imageUrl:     String!
  duration:     String!
  price:        String!
  cities:       [City!]!
  categories:   [TourCategory!]!
  featuredTour: Boolean!
  onSale:                Boolean!
  saleDiscountPercentage: Int
}

type Cruise {
  id:          ID!
  title:       String!
  imageUrl:    String!
  description: String!
  itinerary:   String!
  duration:    String!
  price:       String!
  sourceUrl:   String!
  onSale:                Boolean!
  saleDiscountPercentage: Int
}

type Query {
  tourCategories:                  [TourCategory!]!
  regions:                         [Region!]!
  region(key: String!):            Region
  cities:                          [City!]!
  featuredTour:                    Tour
  toursByCity(cityId: ID!, limit: Int):         [Tour!]!
  toursByCategory(categoryId: ID!, limit: Int): [Tour!]!
  cruises:                         [Cruise!]!
  allTours:                        [Tour!]!
  allCruises:                      [Cruise!]!
  tour(id: ID!):                   Tour
  cruise(id: ID!):                 Cruise
}
